### ISSUE TITLE
Organizers icon highlight

### ISSUE THREAD

**Issue by Ravi2712** [CySoc2022/CySoc2022.github.io#1]
Hovering over organizers single profile-icon(aka Twitter, or Linkedin) shows color on all icons.

**Comment by mr-devs** [comment]
@Ravi2712 as you may have seen in Ugur's email - he'd like to start disseminating information about the workshop ASAP. This is why I sort of did a bum-rush on getting as much finalized as possible. 

Can you please look into this quirk and address it as soon as you can. Unfortunately, this is a bit beyond my front-end knowledge/capabilities.

**Comment by Ravi2712** [comment]
@mr-devs Definitely. I will post you an update by afternoon.

**Comment by Ravi2712** [comment]
Oops! Forgot to add `Close #1` in commit to auto-close. Fixed in commit#8d14f8c190626406d9d03c63e2a3b9da3e601853.
