### ISSUE TITLE
Update Why Attend CySoc Section

### ISSUE THREAD

**Issue by mr-devs** [CySoc2022/CySoc2022.github.io#11]
- [ ] Double-check that the old text is still relevant.
    - [ ] Compare 2021 to 2020 format. If they are identical, leave it the same.

**Comment by Ravi2712** [comment]
[UPDATE]: `Why Attend` text on 2020 website, 2021 website and current 2022 website matches exactly. If the text is relevant according to you, feel free to close this issue. :)

**Comment by mr-devs** [comment]
Thanks. Leaving same as last year.
