### ISSUE TITLE
Update top-left ICWSM image

### ISSUE THREAD

**Issue by mr-devs** [CySoc2022/CySoc2022.github.io#2]
The ICWSM image in the top-left corner of the site is for 2020, need to update this for 2021. 

I am not sure if there is an official place to get this image from. May need to check with Ugur for this.

- [ ] Get new image (Matt)
- [ ] Update image (Jay)

**Comment by Ravi2712** [comment]
@mr-devs Also, just wanted to make a note that image shows Atlanta, I guess. Maybe new image could have the city conference will be in. :)

**Comment by mr-devs** [comment]
Yeah, my guess is that they do something similar to what you've described. This year's conference is actually in Atlanta again. However, the dates are wrong. I suspect that the conference may release these images like these for others to use but I'm not sure. It seems unlikely that one of us created this in the past but I could be wrong.

**Comment by Ravi2712** [comment]
Lemme give a try to change the logo image. I know some quick tools that I tried before. Might save your time to get a new image. :)

**Comment by mr-devs** [comment]
Thanks for the initiative, Jay. That said, why don't you hold off on that for now. If ICWSM does release official images like I described, then we will need to use those anyway.

**Comment by Ravi2712** [comment]
Oh, I see. That's fair.

**Comment by mr-devs** [comment]
Addressed in #15
