### ISSUE TITLE
Update buttons across the top of the page

### ISSUE THREAD

**Issue by mr-devs** [CySoc2022/CySoc2022.github.io#3]
If you compare the buttons at the top of [this year's website](https://cysoc2022.github.io/) (e.g., "CySoc Workshop", "Why Attend", etc.)  with the one from [last year](http://cysoc.aiisc.ai/) you'll notice some differences.

- [x] Update the text to match last year's format
- [x] Make sure to include a button that links to last year's workshop page

**Comment by Ravi2712** [comment]
@mr-devs I had to play hide n seek to find out what was the difference, lol. I think the difference is not the font(aka text format) but there are two separate button for **Program** and **Organization**. I will take care of this as a separate PR to make sure everything looks good. 👍

**Comment by mr-devs** [comment]
Sorry, if the differences weren't clear!

A separate PR sounds like a great idea. Thanks!!

**Comment by Ravi2712** [comment]
No worries. Just mentioning to have a noted comment! So, I don't forget. :)

**Comment by mr-devs** [comment]
Just to be clear, there is an **additional button** on the 2021 site which links to 2020 site, we want to make sure that we include a similar button that links from the 2022 site to the 2021 site.

**Comment by Ravi2712** [comment]
@mr-devs Sure. I updated that, you should be able to see that now! I think it takes just a while before website gets refreshed after merging to `main`. :)

**Comment by mr-devs** [comment]
okay, great! I see it now. Thanks!
